Clone table
mate-academy/js_task_clone_table_column_DOM pull request #160
Opened 2021-04-27 18:01 UTC by ivan-major

2021-04-28 08:30 UTC, vpolets requested changes

2021-04-28 08:30 UTC, vpolets commented on src/scripts/main.js
> +};
скороти код до 3-4 рядків.
Ти можеш дістати всі tr на сторінці чи в конкретній таблиці і просто клонувати у них потрібну тобі клітинку

2021-04-28 09:29 UTC, ivan-major commented on src/scripts/main.js
> +};
Дякую за підказку. 
Дійсно, я накрутив аж занадто. Код можна вмістити в 4 рядки

2021-04-29 14:16 UTC, vpolets approved these changes

2025-01-26 13:12 UTC, closed without merging