done
mate-academy/js_task_clone_table_column_DOM pull request #39
Opened 2020-10-06 12:37 UTC by aionova

- [DEMO LINK](https://aionova.github.io/js_task_clone_table_column_DOM/)

2020-10-06 15:07 UTC, yazheviks approved these changes
Классно)

2020-10-08 07:05 UTC, solaryasha requested changes
Це завдання краще зробити без `querySelectorAll`.
Вибери за допомогою `querySelector` таблицю і застосовуй [властивості](https://javascript.info/dom-navigation#dom-navigation-tables) таблиці

2020-10-08 09:38 UTC, solaryasha requested changes

2020-10-08 09:38 UTC, solaryasha commented on src/scripts/main.js
> +  table.rows[i].children[4].before(itemToCopy.cloneNode(true));
Що таке 4 ?

2020-10-08 09:38 UTC, solaryasha commented on src/scripts/main.js
> +  const itemToCopy = table.rows[i].cells[1];
Що таке 1 ?

2020-10-08 09:41 UTC, aionova commented on src/scripts/main.js
> +  table.rows[i].children[4].before(itemToCopy.cloneNode(true));
нам нужно скопировать столбик с индексом 1 в столбик перед индексом 4. записать в переменнные эти индексы?

2020-10-08 09:53 UTC, solaryasha commented on src/scripts/main.js
> +  table.rows[i].children[4].before(itemToCopy.cloneNode(true));
Звісно @aionova

2020-10-08 10:05 UTC, solaryasha approved these changes

2023-09-27 09:09 UTC, closed without merging