Develop js_task_clone_table_column_DOM
mate-academy/js_task_clone_table_column_DOM pull request #605
Opened 2023-03-20 13:19 UTC by sergey-lipikhin

[DEMO LINK](https://sergey-lipikhin.github.io/js_task_clone_table_column_DOM/)

2023-03-24 13:55 UTC, sergii-nosachenko requested changes
Can be improved

2023-03-24 13:55 UTC, sergii-nosachenko commented on src/scripts/main.js
> +function CloneElementOfRow(row) {
```suggestion
function CloneElementOfRows(rows, from, to) {
```
Pass an array here and loop through it.

2023-03-24 13:55 UTC, sergii-nosachenko commented on src/scripts/main.js
> +[...tableBodyRowElements].forEach(CloneElementOfRow);
```suggestion
[tHead, ...tBodies, tFoot].forEach(
  ({ rows }) => CloneElementOfRows(rows, columnIndexToClone, columnIndexRecipient),
);
```

2023-03-29 10:55 UTC, illiarerun approved these changes
GJ

2024-03-20 11:21 UTC, closed without merging